# Generated by Django 4.0.1 on 2022-06-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Class', models.CharField(max_length=10)),
                ('Division', models.CharField(max_length=10)),
                ('Gender', models.CharField(max_length=20)),
                ('Admission_No', models.CharField(max_length=10)),
            ],
        ),
    ]
