# Generated by Django 4.0.1 on 2022-06-09 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='DOB',
            field=models.DateField(default=datetime.date),
        ),
    ]
